networks:
  default:

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - default
    depends_on:
      - service-a
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    image: redis
    container_name: redis
    networks:
      - default

  service-a:
    build: ./service-a
    image: service-a
    container_name: service-a
    networks:
      - default
    depends_on:
      - service-b
      - redis
      - otel-collector
      - promtail
    environment:
      - PORT=3000
      - SERVICE_B_URL=http://service-b:3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_NAME=service-c-queue
      - OTEL_COLLECTOR_URL=http://otel-collector:4318
      - OTEL_SERVICE_NAME=service-a

  service-b:
    build: ./service-b
    image: service-b
    container_name: service-b
    depends_on:
      - otel-collector
      - promtail
    networks:
      - default
    environment:
      - PORT=3000
      - OTEL_COLLECTOR_URL=http://otel-collector:4318
      - OTEL_SERVICE_NAME=service-b

  service-c:
    build: ./service-c
    image: service-c
    container_name: service-c
    depends_on:
      - redis
      - otel-collector
      - promtail
    networks:
      - default
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_NAME=service-c-queue
      - OTEL_COLLECTOR_URL=http://otel-collector:4318
      - OTEL_SERVICE_NAME=service-c

  otel-collector:
    image: otel/opentelemetry-collector
    container_name: otel-collector
    depends_on:
      - jaeger
    networks:
      - default
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./open-telemetry/otel-collector-config.yml:/etc/otel-collector-config.yml:ro

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    networks:
      - default
    ports:
      - 8082:16686 # Jaeger UI

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - otel-collector
    networks:
      - default
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  promtail:
    image: grafana/promtail
    container_name: promtail
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
    command:
      - -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  loki:
    image: grafana/loki
    container_name: loki
    networks:
      - default
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
      - jaeger
      - loki
    networks:
      - default
    ports:
      - 8081:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:

  k6:
    build: ./k6
    container_name: k6
    networks:
      - default
    depends_on:
      - nginx
