receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:

  otlphttp:
    endpoint: "http://jaeger:4318"
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:9464"

processors:
  batch:
    timeout: 5s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
