{
 "title": "Default",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Throughput - Service A",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_count{exported_job=\"service-a\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - Service A",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"service-a\", http_method=\"GET\"}[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"service-a\", http_method=\"GET\"}[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"service-a\", http_method=\"GET\"}[1m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Dependency latency - Service A",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, net_peer_name) (rate(http_client_duration_milliseconds_bucket{exported_job=\"service-a\"}[1m])))",
     "legendFormat": "{{net_peer_name}}"
    }
   ]
  },
  {
   "title": "Throughput - Service B",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_count{exported_job=\"service-b\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - Service B",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"service-b\", http_method=\"GET\"}[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"service-a\", http_method=\"GET\"}[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"service-a\", http_method=\"GET\"}[1m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Total Generated Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "expr": "sum(generated_number_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Received events - Service C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(queue) (event_freshness_milliseconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event freshness - Service C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(event_freshness_milliseconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(event_freshness_milliseconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(event_freshness_milliseconds_bucket[1m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Logs - Service A",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{container=\"/service-a\"} | json"
    }
   ]
  },
  {
   "title": "Logs - Service B",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{container=\"/service-b\"} | json"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{container=\"/service-a\"}"
    }
   ]
  }
 ]
}